export enum ComponentTypeEnum {
  INPUT_TEXT= 'INPUT_TEXT',
  MULTIPLE_BUTTONS= 'MULTIPLE_BUTTONS',
  CHECKBOXES= 'CHECKBOXES',
  DROPDOWN = 'DROPDOWN',
  TEXTAREA = 'TEXTAREA',
  PICTURE = 'PICTURE',
  DATE = 'DATE',
  DATE_TIME = 'DATE_TIME',
  NUMBER = 'NUMBER',
  SIGNATURE = 'SIGNATURE'
}
